# B''H

## House Prices - EDA

**Step 4: Handle missing data.**

Important questions when thinking about missing data:
- How prevalent is the missing data?
- Is missing data random or does it have a pattern?

Missing data can imply a reduction of the sample size. This can prevent us from proceeding with the analysis. 

Moreover, from a substantive perspective, we need to ensure that the missing data process is not biased and hiding other flaws in the data.

**Key Takeaway:** 
- We ended up dropping 18 variables (columns) and 1 observation (record)

In [1]:
import os
import sys

import math

import numpy as np
import pandas as pd

from scipy import stats

import matplotlib.pyplot as plt

import seaborn as sns

---
## Set the plot output sizes

In [2]:
# Get current size
fig_size = plt.rcParams["figure.figsize"]
 
# Prints: [8.0, 6.0]
print ("Prior size:", fig_size)
 
# Set figure width to 12 and height to 9
fig_size[0] = 12
fig_size[1] = 9
plt.rcParams["figure.figsize"] = fig_size

print ("Current size:", fig_size)

Prior size: [6.0, 4.0]
Current size: [12, 9]

---
## Get project info

In [3]:
NOTEBOOKS_DIR = os.path.join(os.pardir)

print(os.path.abspath(NOTEBOOKS_DIR))

/home/laz/repos/springboard-mini-projects/notebooks

In [4]:
PROJ_ROOT = os.path.join(NOTEBOOKS_DIR,os.pardir)

print(os.path.abspath(PROJ_ROOT))

/home/laz/repos/springboard-mini-projects

In [5]:
# add the 'src' directory as one where we can import modules
SRC_DIR = os.path.join(PROJ_ROOT, 'src')
sys.path.append(SRC_DIR)

print(os.path.abspath(SRC_DIR))

/home/laz/repos/springboard-mini-projects/src

In [6]:
# Load the "autoreload" extension
%load_ext autoreload

# always reload modules marked with "%aimport"
%autoreload 1

# import my method from the source code
%aimport helper_functions
import helper_functions as hf

---
### Import the data:

In [9]:
df_train = hf.read_csv(
    p_dir       = hf.DATA_INTERIM_DIR,
    p_file_name = 'df_train_step_03.csv',
    p_index_col = 'Id'
)

df_train.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ExterQualRecode,ExterCondRecode,BsmtQualRecode,BsmtCondRecode,HeatingQCRecode,KitchenQualRecode,FireplaceQuRecode,GarageQualRecode,GarageCondRecode,PoolQCRecode
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,4,3,4.0,3.0,5,4,NaN,3.0,3.0,NaN
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,3,3,4.0,3.0,5,3,3.0,3.0,3.0,NaN
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,4,3,4.0,3.0,5,4,3.0,3.0,3.0,NaN
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,3,3,3.0,4.0,4,4,4.0,3.0,3.0,NaN
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,4,3,4.0,3.0,5,4,3.0,3.0,3.0,NaN

---
## Show missing data counts

In [17]:
total = df_train.isnull().sum().sort_values(ascending=False)

percent = (df_train.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)

In [30]:
missing_data = pd.concat(
    [total, percent], 
    axis = 1, 
    keys = ['Total', 'Percent']
)

missing_data = missing_data[missing_data['Total'] > 0]

missing_data

                   Total   Percent
PoolQCRecode        1453  0.995205
MiscFeature         1406  0.963014
Alley               1369  0.937671
Fence               1179  0.807534
FireplaceQuRecode    690  0.472603
LotFrontage          259  0.177397
GarageType            81  0.055479
GarageFinish          81  0.055479
GarageCondRecode      81  0.055479
GarageYrBlt           81  0.055479
GarageQualRecode      81  0.055479
BsmtFinType2          38  0.026027
BsmtExposure          38  0.026027
BsmtQualRecode        37  0.025342
BsmtCondRecode        37  0.025342
BsmtFinType1          37  0.025342
MasVnrArea             8  0.005479
MasVnrType             8  0.005479
Electrical             1  0.000685

---
### Note how the missing Garage% data refer to the same set of observations

In [28]:
fields = ['GarageType', 'GarageFinish', 'GarageCondRecode', 'GarageYrBlt', 'GarageQualRecode']

df_train[df_train['GarageType'].isnull()][fields]

     GarageType GarageFinish  GarageCondRecode  GarageYrBlt  GarageQualRecode
Id
40          NaN          NaN               NaN          NaN               NaN
49          NaN          NaN               NaN          NaN               NaN
79          NaN          NaN               NaN          NaN               NaN
89          NaN          NaN               NaN          NaN               NaN
90          NaN          NaN               NaN          NaN               NaN
100         NaN          NaN               NaN          NaN               NaN
109         NaN          NaN               NaN          NaN               NaN
126         NaN          NaN               NaN          NaN               NaN
128         NaN          NaN               NaN          NaN               NaN
141         NaN          NaN               NaN          NaN               NaN
149         NaN          NaN               NaN          NaN               NaN
156         NaN          NaN               NaN          NaN               NaN
164         NaN          NaN               NaN          NaN               NaN
166         NaN          NaN               NaN          NaN               NaN
199         NaN          NaN               NaN          NaN               NaN
211         NaN          NaN               NaN          NaN               NaN
242         NaN          NaN               NaN          NaN               NaN
251         NaN          NaN               NaN          NaN               NaN
288         NaN          NaN               NaN          NaN               NaN
292         NaN          NaN               NaN          NaN               NaN
308         NaN          NaN               NaN          NaN               NaN
376         NaN          NaN               NaN          NaN               NaN
387         NaN          NaN               NaN          NaN               NaN
394         NaN          NaN               NaN          NaN               NaN
432         NaN          NaN               NaN          NaN               NaN
435         NaN          NaN               NaN          NaN               NaN
442         NaN          NaN               NaN          NaN               NaN
465         NaN          NaN               NaN          NaN               NaN
496         NaN          NaN               NaN          NaN               NaN
521         NaN          NaN               NaN          NaN               NaN
...         ...          ...               ...          ...               ...
955         NaN          NaN               NaN          NaN               NaN
961         NaN          NaN               NaN          NaN               NaN
969         NaN          NaN               NaN          NaN               NaN
971         NaN          NaN               NaN          NaN               NaN
977         NaN          NaN               NaN          NaN               NaN
1010        NaN          NaN               NaN          NaN               NaN
1012        NaN          NaN               NaN          NaN               NaN
1031        NaN          NaN               NaN          NaN               NaN
1039        NaN          NaN               NaN          NaN               NaN
1097        NaN          NaN               NaN          NaN               NaN
1124        NaN          NaN               NaN          NaN               NaN
1132        NaN          NaN               NaN          NaN               NaN
1138        NaN          NaN               NaN          NaN               NaN
1144        NaN          NaN               NaN          NaN               NaN
1174        NaN          NaN               NaN          NaN               NaN
1180        NaN          NaN               NaN          NaN               NaN
1219        NaN          NaN               NaN          NaN               NaN
1220        NaN          NaN               NaN          NaN               NaN
1235        NaN          NaN               NaN          NaN               NaN
1258        NaN          NaN               NaN          NaN               NaN
1284        NaN          NaN               NaN          NaN               NaN
1324        NaN          NaN               NaN          NaN               NaN
1326        NaN          NaN               NaN          NaN               NaN
1327        NaN          NaN               NaN          NaN               NaN
1338        NaN          NaN               NaN          NaN               NaN
1350        NaN          NaN               NaN          NaN               NaN
1408        NaN          NaN               NaN          NaN               NaN
1450        NaN          NaN               NaN          NaN               NaN
1451        NaN          NaN               NaN          NaN               NaN
1454        NaN          NaN               NaN          NaN               NaN

[81 rows x 5 columns]

---
### Note how the missing Bsmt% data refer to the same set of observations (except for one row)

In [29]:
fields = ['BsmtFinType2', 'BsmtExposure', 'BsmtQualRecode', 'BsmtCondRecode', 'BsmtFinType1']

df_train[df_train['BsmtFinType2'].isnull()][fields]

     BsmtFinType2 BsmtExposure  BsmtQualRecode  BsmtCondRecode BsmtFinType1
Id
18            NaN          NaN             NaN             NaN          NaN
40            NaN          NaN             NaN             NaN          NaN
91            NaN          NaN             NaN             NaN          NaN
103           NaN          NaN             NaN             NaN          NaN
157           NaN          NaN             NaN             NaN          NaN
183           NaN          NaN             NaN             NaN          NaN
260           NaN          NaN             NaN             NaN          NaN
333           NaN           No             4.0             3.0          GLQ
343           NaN          NaN             NaN             NaN          NaN
363           NaN          NaN             NaN             NaN          NaN
372           NaN          NaN             NaN             NaN          NaN
393           NaN          NaN             NaN             NaN          NaN
521           NaN          NaN             NaN             NaN          NaN
533           NaN          NaN             NaN             NaN          NaN
534           NaN          NaN             NaN             NaN          NaN
554           NaN          NaN             NaN             NaN          NaN
647           NaN          NaN             NaN             NaN          NaN
706           NaN          NaN             NaN             NaN          NaN
737           NaN          NaN             NaN             NaN          NaN
750           NaN          NaN             NaN             NaN          NaN
779           NaN          NaN             NaN             NaN          NaN
869           NaN          NaN             NaN             NaN          NaN
895           NaN          NaN             NaN             NaN          NaN
898           NaN          NaN             NaN             NaN          NaN
985           NaN          NaN             NaN             NaN          NaN
1001          NaN          NaN             NaN             NaN          NaN
1012          NaN          NaN             NaN             NaN          NaN
1036          NaN          NaN             NaN             NaN          NaN
1046          NaN          NaN             NaN             NaN          NaN
1049          NaN          NaN             NaN             NaN          NaN
1050          NaN          NaN             NaN             NaN          NaN
1091          NaN          NaN             NaN             NaN          NaN
1180          NaN          NaN             NaN             NaN          NaN
1217          NaN          NaN             NaN             NaN          NaN
1219          NaN          NaN             NaN             NaN          NaN
1233          NaN          NaN             NaN             NaN          NaN
1322          NaN          NaN             NaN             NaN          NaN
1413          NaN          NaN             NaN             NaN          NaN

---
### Approach taken to handle the missing data in our data:

- **Concerning the cases where more than 15% of the data is missing:**
    - We'll delete those variables completely. 
    - None of these variables seem to be very important, since most of them are not aspects in which we think about when buying a house. 

- **Concerning the Garage% and Bsmt% variables:**
    - The Garage% variables have the same number of missing data. 
    - The missing data refers to the same set of observations. 
    - Since the most important information regarding garages is already expressed by 'GarageCars' and considering that we are just talking about 5% of missing data, we'll delete these.
    - The same logic applies to Bsmt% variables.

- **Concerning the MasVnrArea and MasVnrType:**
    - These variables don't appear to be essential. 
    - Thus, we will not lose information if we delete these.

- **Concerning the MasVnrArea and Electrical:**
    - Since it is just one observation, we'll delete this observation and keep the variable.

---
### Delete columns:

In [32]:
variables_to_drop = (missing_data[missing_data['Total'] > 1]).index

variables_to_drop

Index(['PoolQCRecode', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQuRecode',
       'LotFrontage', 'GarageType', 'GarageFinish', 'GarageCondRecode',
       'GarageYrBlt', 'GarageQualRecode', 'BsmtFinType2', 'BsmtExposure',
       'BsmtQualRecode', 'BsmtCondRecode', 'BsmtFinType1', 'MasVnrArea',
       'MasVnrType'],
      dtype='object')

In [33]:
df_train = df_train.drop(variables_to_drop, axis = 1)

---
### Delete rows:

In [36]:
rows_to_drop = df_train.loc[df_train['Electrical'].isnull()].index

rows_to_drop

Int64Index([1380], dtype='int64', name='Id')

In [37]:
df_train = df_train.drop(rows_to_drop)

---
### Confirm no more missing data missing.

In [39]:
df_train.isnull().sum().max()

0

In [40]:
df_train.head()

,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,ExterQualRecode,ExterCondRecode,HeatingQCRecode,KitchenQualRecode
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,2,2008,WD,Normal,208500,4,3,5,4
2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,...,0,5,2007,WD,Normal,181500,3,3,5,3
3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,...,0,9,2008,WD,Normal,223500,4,3,5,4
4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,...,0,2,2006,WD,Abnorml,140000,3,3,4,4
5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,...,0,12,2008,WD,Normal,250000,4,3,5,4

---
### Save to csv

In [41]:
file = os.path.join(hf.DATA_INTERIM_DIR, 'df_train_step_04.csv')

df_train.to_csv(file)